name: andeir_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2 
  url_launcher: ^6.3.0 
  cached_network_image: ^3.3.0
  table_calendar: ^3.0.9
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_fonts: 6.2.1
  cloud_firestore: 5.6.8
  firebase_storage: 12.4.6      
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  intl: ^0.18.1 
  provider: ^6.0.5

dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/default_avatar.png
