name: andeir_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: 5.6.8
  firebase_storage: 12.4.6      
  image_picker: ^1.0.7   

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/default_avatar.png
